# Generated by Django 3.0.1 on 2020-01-02 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commit',
            options={'ordering': ['branch', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='commitfile',
            options={'ordering': ['filename']},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='languagerepo',
            options={'ordering': ['language']},
        ),
        migrations.AlterModelOptions(
            name='org',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='repo',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
    ]
