# Generated by Django 3.0.1 on 2020-01-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200102_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitfile',
            name='action',
            field=models.CharField(choices=[('create', 'create'), ('update', 'update'), ('rename', 'rename'), ('delete', 'delete'), ('help', 'help'), ('other', 'other')], max_length=6),
        ),
        migrations.AlterField(
            model_name='issue',
            name='label',
            field=models.CharField(choices=[('bug', 'bug'), ('feature', 'feature'), ('documentation', 'documentation'), ('help', 'help'), ('other', 'other')], max_length=13),
        ),
        migrations.AlterField(
            model_name='issue',
            name='state',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed')], max_length=6),
        ),
        migrations.AlterField(
            model_name='owner',
            name='type',
            field=models.CharField(choices=[('user', 'user'), ('org', 'org')], max_length=4),
        ),
    ]
